services:
  postgre:
    image: postgres:13.13
    ports:
     - 5432:5432
    networks:
     - kubnews_net
    environment:
      POSTGRES_PASSWORD: pg123
      POSTGRES_USER: kubnews
      POSTGRES_DB: KUBNEWS

  kubnews:
    image: greglixandrao/kube-news:v1
    depends_on:
     - postgre
    build:
      context: ./src
      dockerfile: ./Dockerfile
    networks:
     - kubnews_net
    ports:
     - 8080:8080
    environment:
      DB_DATABASE: KUBNEWS
      DB_USERNAME: kubnews
      DB_PASSWORD: pg123
      DB_HOST: postgre

networks:
  kubnews_net:
    driver: bridge
